"use client"

import "./globals.css"
import Lenis from "lenis"
import { useState, useEffect } from "react"
import Navbar from "@/components/Navbar"

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
	const [pageReady, setPageReady] = useState(false)

	const getPageReady = () => {
		setTimeout(() => {
			setPageReady(true)
			console.log('page ready')
		},500)
	}
	
	useEffect(() => {
		const lenis = new Lenis({
			autoRaf: true,
		})

		if (!window.UnicornStudio) {
			window.UnicornStudio = { isInitialized: false }
			const script = document.createElement('script')
			script.src = 'https://cdn.jsdelivr.net/gh/hiunicornstudio/unicornstudio.js@v1.4.20/dist/unicornStudio.umd.js'
			script.onload = () => {
				if (!window.UnicornStudio.isInitialized) {
					UnicornStudio.init()
						.then(() => {
							getPageReady()
						})
						.catch((err) => {
							console.error(err)
						})
					window.UnicornStudio.isInitialized = true
				}
			}
			(document.head || document.body).appendChild(script)
		}
		return () => {
			lenis.destroy()
		}
	}, [])

	return (
		<html lang="en">
			<head>
				<link rel="preconnect" href="https://fonts.googleapis.com" />
				<link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
				<link href="https://fonts.googleapis.com/css2?family=Bricolage+Grotesque:opsz,wght@12..96,200..800&family=Space+Grotesk:wght@300..700&display=swap" rel="stylesheet" />
			</head>
			<body className={`antialiased`}>
				{!pageReady && <div className="h-screen w-full bg-[var(--background)] fixed z-[1000]">loading</div>}
				<Navbar/>
				{children}
			</body>
		</html>
	)
}
